name: CI/CD

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with make
        run: make && make test-bin

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            freq-counter
            tests/test_runner
            tests/run.sh

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Make files executable
        run: |
          chmod +x tests/run.sh
          chmod +x tests/test_runner

      - name: Run tests
        run: ./tests/run.sh
  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build release binary
        run: make

      - name: Package for release
        run: tar -czvf ${{ github.ref_name }}.tar.gz freq-counter

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.ref_name }}.tar.gz